In [2]:
import numpy as np

In [18]:
print(np.array([1, 2, 3, 4, 5]))
print(np.zeros(5))
print(np.ones((3, 3)))
print(np.arange(0, 10, 2))
print(np.linspace(0, 1, 5))

[1 2 3 4 5]
[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


In [24]:
a = np.array([10, 20, 30, 40, 50])
print(a * 2)
print(a + 100)
print(a ** 2)
print(a / 10)

[ 20  40  60  80 100]
[110 120 130 140 150]
[ 100  400  900 1600 2500]
[1. 2. 3. 4. 5.]


In [28]:
a = np.array([10, 20, 30, 40, 50])
print(a[0])
print(a[-1])
print(a[1:4])
print(a[a > 20])

10
50
[20 30 40]
[30 40 50]


In [34]:
a = np.array([10, 20, 30, 40, 50])
print(np.mean(a))
print(np.std(a))
print(np.max(a))
print(np.min(a))
print(np.sum(a))
print(np.cumsum(a))

30.0
14.142135623730951
50
10
150
[ 10  30  60 100 150]


In [40]:
def portfolio_stats(returns):
    mean_return = np.mean(returns)
    std_return = np.std(returns)
    ann_return = mean_return * 252
    ann_volatility = std_return * np.sqrt(252)

    print(f"Mean Daily Return:       {mean_return:.4f}")
    print(f"Daily Std Dev:           {std_return:.4f}")
    print(f"Annualised Return:       {ann_return:.4f}")
    print(f"Annualised Volatility:   {ann_volatility:.4f}")

# Test it
sample_returns = np.array([0.01, -0.005, 0.02, -0.01, 0.015, 0.008, -0.003])
portfolio_stats(sample_returns)

Mean Daily Return:       0.0050
Daily Std Dev:           0.0103
Annualised Return:       1.2600
Annualised Volatility:   0.1641
